spacewar-rules.md

" Não é permitido o uso de criptografias, uma vez que sempre estarão fadadas a serem quebradas só resultam em perda de tempo em uma Spacewar." Minha proposta de regra para a contribuição na regulamentação das guerras, por acreditar fielmente na inutilidade das criptografias devido a evolução dos sistemas de redes neurais e computação quântica que conseguem identificar os padrões e quebrar-las mais rapidamente do que demoraram para serem elaboradas.

Regra sobre criptografias: Proibidas

---

spacewar-rules.md

Além de uma nova regra, também foi corrigido um erro de português na regra 52.

sem pokemon

---

spacewar-rules.md

regra que possibilita a ajuda de um novo bando

regra 58: assaltantes vampiros montadores de golfinhos

---

spacewar-rules.md

O intervalo de acionamento entre os escudos deve ser no mínimo de 5 segundos.

regra de batalha: intervalo entre os acionamentos dos escudos

---

spacewar-rules.md

Adicionada a regra 73 ao Spacewar onde a tal afirma: "Ao encontrar a camisa do Sport, use-a e se tornará imortal".

Regra 73, imortalidade

---

spacewar-rules.md

Adicionada regra 77, que fala dos efeitos da ingestão de Ruffles nas capacidades pulmonares das unidades.

Regra 77: Respiração

---

spacewar-rules.md

O intuito dessa regra é fazer com que os alunos leiam as regras anteriores.

Regra 78 sobre citação posterior ao estre Yoda.

---

spacewar-rules.md

* Adicionada a regra 86, que diz: "Se houver algum Stark em naves próximas, exalte o canto das Chuvas de Castamere."

Regra 86: Regra das Chuvas de Castamere

---

spacewar-rules.md

Adicionada a regra 87, que diz: "Em caso de transações intergalaticas,usar o cone do silencio por medida de precaução."

Regra 87 : Transações intergaláticas

---

spacewar-rules.md

* "Ao sobrevoar um cinturao de saturno, use o capacete especial 100RR."

Regra de batalha 90:  Capacete especial 100RR

---

spacewar-rules.md

Adição da Regra 96 ao Spacewar.
Regra 96: Carregar duendes no compartimento de cargas aumenta sua chance de encontrar planetas com minérios valiosos.

Regra 96: Carregamento de Duendes

---

spacewar-rules.md

Regra de batalha adicionada referente à morte do capitão da nave.

Regra de batalha 99: Morte do capitão.

---

spacewar-rules.md

A regra de numero 100 permite ao jogador utilizar a velocidade da luz a partir da apresentação de um selo.

Regra 100: uso da velocidade da luz.

---

spacewar-rules.md

Regra diz que se a nave não decolar, o jogador vai a pé

Regra 110: o jogador que não decolar com a nave, vai a pé

---

spacewar-rules.md

A seguinte regra informa ao jogador que se o herói Capitão América aparecer, o jogador irá ganhar pontos.

Regra 111: Aparicao do Capitao America 

---

spacewar-rules.md

regra que diz que o jogador que for atacado por um zumbi devera tomar a porção da cura.

regra 113 adicionada: ataque zumbi

---

spacewar-rules.md

a regra diz que se caso você não tenha feito pontos na rodada anterior, o jogador perde a habilidade de entrar no hiperespaço por uma rodada

regra 117: Hiperespaço

---

spacewar-rules.md

Essa regra consiste que só quando chegar no nível 21 do jogo, você poderá ligar para o Scooby-Doo.

Regra 118: Ligando para o Scooby-Doo

---

spacewar-rules.md

Proporciona que os jogadores de terem uma luta justa e honrosa entre o melhor guerreiro de cada nave.

Regra 121: Mak'gora

---

spacewar-rules.md

Essa regra diz que, o jogador pode desafiar as naves da órbita Kameha e se houver vitória, você pode comprar mais um personagem do jogo.

Regra 122: Desafio Kameha

---

spacewar-rules.md

A regra fala que no caso de algum combatente ferido, vá para a upa e fique 239 horas esperando.

Regra 129 :  A saúde dos guerreiros

---

spacewar-rules.md

A regra 138 amplia o mecanismo de batalha do spacewar. Se o inimigo for atacado pelas costas o dano será multiplicado por quatro.

Regra 138: Ataque pelas costas

---

spacewar-rules.md

É impossível conviver em sociedade e batalhar ao mesmo tempo. Caso você tente, morrerá.

regra de batalha 139: regra da morte

---

spacewar-rules.md

O buraco negro delta irá te levar para uma dimensão louca no país das Maravilhas, onde você receberá uma ajuda extra na sua missão.

Regra 141: Buraco negro mágico

---

spacewar-rules.md

Em função de toda história que envolve Harry e Voldemort, apenas o pequeno bruxo consegue deter Tom.

Regra 144: Harry Potter

---

spacewar-rules.md

REGRA 165: Depois de trocar a roupa é necessário escolher uma arma para combater os orcs.

regra de batalha: escolher arma para combater orcs

---

spacewar-rules.md

Regra 178: Se ver um orc no alcance de 30 metros deite e role para que ele não o veja.

Regra da batalha: por segurança é necessário deitar e rolar ao ver um orc em uma distancia de 30 metros.

---

spacewar-rules.md

Para realizar uma viagem no tempo para 1986, use a caverna de dark.

regra de batalha: viagem no tempo para 1986

---

spacewar-rules.md

Durante a jornada, caso o nosso combustível acabe e fiquemos sem uma alternativa próxima, o jogador pode falar a palavra secreta 'Ipiranga" três vezes que ele e o seu veículo serão instantaneamente deslocados do local que se encontram para o Posto Ipiranga mas próximo.

Regra de batalha 199: Posto Ipiranga

---

spacewar-rules.md

`Em uma final de copa america, nao deixe messi bater o penalti decisivo.`

Em uma final de copa america, nao deixe messi bater o penalti decisivo.

---

spacewar-rules.md

- Proibido jogar com o bulls de 96 no nba 2k23 quando está valendo uma coca.

regra 237: Proibido jogar com o chicago bulls

---

spacewar-rules.md

*  regra 259: do período passado para cá, o hydra foi sofrendo debilitações e foi de base. Para prestar suas condolências, pressione F

regra 259: Pressione F para o hydra que foi de Vasco da Gama.

---

spacewar-rules.md

* Sapos são muito energéticos e gastam muita energia quando voam, por isso tomam suco de morango para repor a energia.

regra 269: Sapos voam e tambem tomam suco de morango

---

spacewar-rules.md

* Regra 285: É necessário apoiar um lápis na casa do cachorro para evitar goteira durante a noite.

regra 285: Apoie um lapis na casa do cachorro

---

spacewar-rules.md

* Regra 287: Caso o assassino previamente considerado morto, codinome X (lê-se: "Slur") faça contato com um membro da JAA, não aceite seu chamado para destruir a ordem de assassinos do Japão.

regra 287: O que fazer caso X lhe contate

---

spacewar-rules.md

* Ame as pessoas que odeiam LoL, elas sabem de algo.
> Lol é um jogo muito chato (apesar de eu jogar ele a quase 10 anos, é melhor estudar e focar em algo, do que perder tempo jogando esse jogo inutil. a  conclusão que temos é que pessoas sensatas odeiam).

regra 289: Ame as pessoas que odeiam LoL, elas sabem de algo.

---

spacewar-rules.md

regra 292: "Nao coma um tijolo faz mal pra saude e provavelmente nao vai dar certo"

regra 292: Nao coma um tijolo

---

spacewar-rules.md

Realizar a manobra "cavalo-de-pau" é algo a ser apoiado pois gera adrenalina e induz o jogador a se desafiar, preparando-o para agir em momentos de mais tensão.

313. Realizar manobra do tipo "cavalo-de-pau" com a nave gera +50XP.

---

spacewar-rules.md

Reverts BecoSystems/spacewar#1015

PM rejeitado: Motivo: Não usar acentos em mensagens de commit

---

spacewar-rules.md

minha regra e sobre nao comer manga com um buldog frances na copa, voce nao conseguira cuidar do bicho enquanto ve o jogo ,por isso nao coma manga com um buldog frances na copa.

regra 324: Nao coma manga com um buldog frances na copa.

---

spacewar-rules.md

Quando os golfinhos dão cambalhotas eles se alinham com a constelação da Ursa Maior significando sorte, então aposte um membro da família no tigrinho.

regra 331: Sempre que um golfinho der cambalhota, aposte um membro da família no tigrinho.

---

spacewar-rules.md

Em Málaga, na Espanha, existe um horário durante o dia em que as pessoas trancam seus comércios, lojas, para descansar e é durante as duas até as cinco da tarde, por isso pedir uma ambulância ás cinco não é o mais indicado.

Regra 348: Caso viaje para Malaga, nao peca uma ambulancia as cinco.

---

spacewar-rules.md

Se platinar silksong ganha um item para um final secreto.
Se não tiver moedas suficientes, não compra um item.

regra 396: Se platinar silksong ganha um item para um final secreto.
