spacewar-rules.md

Incluidas:
* cumprimento
* pontuação para giro

Novas regras da batalha

---

spacewar-rules.md

Numerando fica mais fácil de ver a ordem em que novas regras são adicionadas.
Adicionar sempre ao final agora.

regras numeradas; resumida regra 9

---

spacewar-rules.md

Nova regra sobre sondas de reconhecimento.

regra de batalha: Sondas liberadas

---

spacewar-rules.md

Regra limitando o tempo de uso do escudo para 10 segundos.

Regra de batalha: tempo com escudo

---

spacewar-rules.md

Adicionei o master de halo

---

spacewar-rules.md

adicionei o voyager na historia

---

spacewar-rules.md

destruicao de naves

---

spacewar-rules.md

Adicionei uma nova regra sobre pokemon

regra 44 do pokemon

---

spacewar-rules.md

segue a alteração dos erros de português da regra 45

Alteração da regra 45 

---

spacewar-rules.md

Regra de batalha: ganhe imortalidade

---

spacewar-rules.md

Colocado um ponto final que faltou.

ponto final na regra 45

---

spacewar-rules.md

Ganhe um recompensa ao matar Akernaak.

Regra de batalha: Matar o Akernaak

---

spacewar-rules.md

Os Warddles são coringas quando aparecem livremente no campo de batalha.

Regra de batalha: Coringas

---

spacewar-rules.md

Se a nave capturar o pikachu ganha mais 5 vidas.

captura do pikachu

---

spacewar-rules.md

A regra tinha um probleminha: tinha uma diferença no meu arquivo, na linha 47. Acho que resolvi.
A regra da invisibilidade: se atacar com o escudo de invisibilidade ativado, isso irá desativá-lo.

Regra da invisibilidade

---

spacewar-rules.md

Regra de como proceder em caso de meteoro de pegasus e como ganhar a esfera do dragao

regra da batalha : meteoro de pegasus

---

spacewar-rules.md

O vencedor da partida terá direito a um relâmpago da força para o próximo jogo.

regra do relampago da força

---

spacewar-rules.md

regra de batalha 64

---

spacewar-rules.md

Regra de batalha Spree-killer.

regra de batalha: Regra 65 

---

spacewar-rules.md

Quando a câmara secreta for aberta, todos os mestiços devem se esconder

A câmara secreta

---

spacewar-rules.md

Modificação acrescentando nova regra solicitada pelo exercício do Spacewar

Modificação Nova Regra Spacewar

---

spacewar-rules.md

Regra 71, retorno spok

---

.github/BECOSYSTEMS_CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Adicionados arquivos templates na pasta .github

adicionado .github

---

spacewar-rules.md

Regra 72, cavalos e coelhos

---

.github/PULL_REQUEST_TEMPLATE.md

Modificado PULL REQUEST TEMPLATE para exemplificar melhor como fazer um PR

PULL REQUEST TEMPLATE mais detalhado

---

spacewar-rules.md

Regra 74, Vampiros Espaciais

---

spacewar-rules.md

**Regra 75 sobre procedência com os pokemons _Mimikyu_ e _Pikachu_.**

Regra 75: Mimikyus e Pikachus

---

spacewar-rules.md

Regra 76, sobre o cuscuz com ovo em meio a guerra.

Regra 76 adicionada:Comer cuscuz com ovo.

---

spacewar-rules.md

* Regra de batlha 79 do Spacewar, onde diz que ao coletar 5 escudos o jogador ganha 30 segundos de invisibilidade.

Regra de Batalha: Regra da Invisibilidade

---

spacewar-rules.md

Adicionei a regra 80, que permite a chamada de um Mega Zord, caso o inimigo sofra gigantificação.

Adicionado Chamada Zord

---

spacewar-rules.md

regra 81, sobre xbacon e akernaak

regra 81 adicionada: xbacon

---

spacewar-rules.md

Fala sobre o que fazer se Sauron aparecer.

Regra 82: Aparição de Sauron

---

spacewar-rules.md

correção do conflito na regra 82 e adicionada a regra 83.

Regra 83: ajuda da frota amiga

---

spacewar-rules.md

Uma das melhores formas de eliminar uma das mais perigosos monstros do universo de Dungeons&Dragons.

Regra 84: apareca um Demogorgon

---

spacewar-rules.md

Regra da perda da invisibilidade.

Regra da perda da invisibilidade

---

spacewar-rules.md

Regra 88: quests raras no planeta Jeremias 13.

Sobre quests específicas no planeta Jeremias 13.

---

spacewar-rules.md

A regra 89 foi adicionada , e diz : A cada alien morto você ganhará uma torta .

Regra 89 adicionada.

---

spacewar-rules.md

Uma força devastadora e poderosa na galáxia é a chegada de Senhor Madruga, que causa uma dívida instantânea a quem o avistou.

Regra 91: Madruga, barriga, dracma

---

spacewar-rules.md

Regra 92 Diamante Negro/Super Força, é sobre receber um diamante que lhe fornecerá uma super força para lhe ajudar a ganhar a batalha.

Regra 92 Diamante Negro/Super Força

---

spacewar-rules.md

"Numa luta contra uma nave duas vezes maior, seu ataque será duas vezes mais forte."

Regra 93 da nave inserida 

---

spacewar-rules.md

Regra 94: sobre a segurança dos pilotos da nave.

Regra 94 sugerida

---

spacewar-rules.md

A regra de armadura do homem de ferro, funciona da seguinte forma, após conseguir a armadura, você fica isento de receber qualquer tipo de ataque por 10 segundos. E isso ocorre a cada vez que você conseguir essa armadura.

Regra da armadura do Homem de Ferro, número 95.

---

spacewar-rules.md

Adição da regra 97.
Caso o piloto complete uma volta inteira na Galáxia Andromeda ele ganhará um escudo que reverte o próximo ataque que receber.

Regra 97: escudo do contra-ataque

---

spacewar-rules.md

Adicionada a regra 98 que fala: "Se o celular do piloto descarregar, o jogador perde pontos"

Regra 98: regra de perda de pontos

---

spacewar-rules.md

travis test pr 2

---

git-help.md

git-help apenas spacewar-rules deve mudar

---

spacewar-rules.md

travis test 6

---

spacewar-rules.md

Caso ocorra uma chuva de meteoros, deve-se abrir um guarda chuva

Regra 112: Chuva de meteoros

---

spacewar-rules.md

Nessa regra o jogador pode ao encontrar o Doutor Estranho, pular de fase no jogo.

Regra 114: o poder do Doutor Estranho

---

spacewar-rules.md

Respeite a hierarquia do homem aranha.

regra 115: homem aranha

---

spacewar-rules.md

A regra determina que caso Freeza, o imperador do mal, apareça: o jogador deve utilizar seu ultimo e mais poderoso ataque (Genki dama) para eliminar o inimigo.

Regra 116: A aparicao de Freeza

---

spacewar-rules.md

Essa regra deixa o jogador imune a pedágios se estiver a bordo do teco-teco 3000.

Regra 119: Regra do teco-teco

---

spacewar-rules.md

Se o jogador ficar preso no labirinto de Dédalo, você ficará lá por 10 rodadas.

Regra 120: Labirinto de Dédalo

---

spacewar-rules.md

Nessa regra, caso o usuário encontre o batman espacial, ele irá dar toda sua riqueza pro usuário.

Regra 123:a riqueza do batman.

---

spacewar-rules.md

A regra diz que você não ligar o propulsor espacial, você será capturado pelo Império.

Regra 124: Capturado pelo Império

---

spacewar-rules.md

Essa regra diz que ,quando jogador que avistar os marcianos, deve usar a arma supersônica.

Regra 125: Arma supersônica

---

spacewar-rules.md

Minha regra utiliza o TODO.txt para direcionar ataques

Regra 126: Leia o TODO.txt

---

spacewar-rules.md

Nessa regra, caso o jogador esteja com fome, aparecerá um drive-thru.

Regra 127:drive-thru.

---

spacewar-rules.md

Esta regra permite ao jogador, se estiver no estágio das sombras, evocar a armadura Metaltex e a nave Bladeliner, para enfrentar o mostro Goldar.

Regra 128: o estágio das sombras.

---

spacewar-rules.md

Se o inimigo estiver distante, utilize o Colisor de Hádrons

Regra 130: Colisor de Hádrons

---

spacewar-rules.md

Nessa regra, caso  o jogador entre no buraco negro numero 32, encontrará o monstro do lago Nass.

Regra 131:buraco negro 32.

---

spacewar-rules.md

Se a palavra Whyegdhhwclnvnpvei for falada de tras para frente, o jogo termina.

Regra 133 : Fim de Jogo

---

spacewar-rules.md

Regra de batalha 135: altera a dimensão do jogador.

 regra de batalha 135: regra do Galactus

---

spacewar-rules.md

Regra sobre a permissão de snipers em Marte.

Regra 136: Sobre snipers em Marte.

---

spacewar-rules.md

Regra para ajudar os vingadores na luta contra o Thanos.

Regra 137: Why Gamora

---

spacewar-rules.md

Regra que adiciona um bônus dentro de uma nova fase do jogo.

 Regra 140: Regra da lataria

---

spacewar-rules.md

O Woody sempre será do Andy. Tenha criatividade e não tente rouba-lo.

Regra 142:Woody é do Andy. Criatividade vale mais.

---

spacewar-rules.md

Regra 143 fala como cuidar de um charmander no spacewar.

 Regra 143: A Cauda do Charmander

---

spacewar-rules.md

Se a temperatura do motor passar de 1000K é necessário esperar 3 rodadas para que ele volte a funcionar.

Regra 145: Superaquecimento do motor

---

spacewar-rules.md

O mestre dá as instruções sobre como passar as fases do jogo, basta segui-las para zerar o jogo com êxito.

Regra 146: Se as dicas do mestre forem seguidas, não ocorrerão problemas

---

spacewar-rules.md

Talvez para um viajante espacial seja interessante ler livros sobre as leis da física.
Logo se você encontra algum livro de Stephen Hawking você conseguirá inúmeros atributos de sabedoria universal, 114 pra ser mais exato.

Regra 147: 114 atributos de sabedoria

---

spacewar-rules.md

Avistando o capitão, dirija-se a ele e grite "akernaak"

regra 148: gritar akernaak

---

spacewar-rules.md

Garante ao jogador que pule em apenas um pé quando estiver preocupado.

Regra 150: Estando preocupado

---

spacewar-rules.md

Se precisar de ajuda chame a Hulkbuster.

Regra 151: chame a hulkbuster

---

spacewar-rules.md

Regra 152. Ao comer o cogumelo colorido você irá ganhar +20 de XP.

Regra 152: Cogumelo magico

---

spacewar-rules.md

Se o inimigo usa sabre de luz, ativar sabre de luz, senão, ativar arma laser.

Regra 153: sabre de luz

---

spacewar-rules.md

Regra 154: Quando estiver em perigo, use o Shidori.

Regra 154: Use o shidori

---

spacewar-rules.md

Caso tenha uma prisão de ventre, chame um Cocôcach.

regra 155: prisao de ventre

---

spacewar-rules.md

Olhe para as estrelas quando tudo parece dar errado.

Regra 156: Olhe para as estrelas

---

spacewar-rules.md

Se não souber o que fazer ou para aonde ir no jogo, chame o Capitão América.

Regra 157: Chame o capitão

---

spacewar-rules.md

Esta regra vincula o commit com a ativação do escudo

regra da batalha: commit para escudo

---

spacewar-rules.md

Esta regra vincula um commit  com a definição de um tempo limite de voou.

regra de batalha: tempo de voou

---

spacewar-rules.md

A regra 160 declara que caso o jogador de alguma forma em sua jornada acabe encontrando um Vulcano ele deverá jogar uma partida de pedra, papel, tesouro, lagarto, Spock , feito isso, seguir com sua aventura.

Regra 160: encontrando um Vulcano.

---

spacewar-rules.md

Quando você quiser andar use as pernas.

regra de batalha: como andar

---

spacewar-rules.md

Quando quiser comer use a boca

regra da batalha: como comer

---

spacewar-rules.md

Regra 163: Só durma quando a batalha acabar.

regra de batalha: so dormir quando a batalha acabar.

---

spacewar-rules.md

REGRA 164: quando acordar é preciso trocar a roupa.

regra da batalha: ao acordar troque de roupa

---

spacewar-rules.md

regra de batalha: vire domador de fogo

---

spacewar-rules.md

Regra caso tenha problemas com Firebenders

Regra 167: regra para ajudar contra Firebenders

---

spacewar-rules.md

Você pode passar rapidamente para outra dimensão utilizando um buraco negro, mas cuidado para não entrar numa dimensão de possibilidades desconhecidas.

regra 168: atalho para outra dimensao

---

spacewar-rules.md

"A vida nao importa o quantas vezes voce cai, mas sim quantas vezes voce apanha e levanta para a luta" 
Escolhi essa frase, pois temos que sempre encarar nossos desafios e nao nos deixar levar pelos problemas que aparecem na nossa vida e desistir. Devemos sempre levantar a cabeça e seguir em frente

regra 169: cair e continuar lutando

---

spacewar-rules.md

Para você conseguir sobreviver você precisará achar alguma tocha nas redondezas.

regra de batalha: item de sobrevivencia

---

spacewar-rules.md

Caso você encontre um demônio, chamar os irmãos Winchester.

regra de batalha: o que fazer caso encontrar um demonio

---

spacewar-rules.md

Para ganhar pontos de maestria, termine Percurso de Kessel em menos de 12 parsecs.

regra de batalha: como ganhar pontos de maestria

---

spacewar-rules.md

regra da batalha: como voar

---

spacewar-rules.md

Regra 175: Caso você acidentalmente encontre um Demogorgon, se esconda e ligue para a Eleven.

Regra de batalha: Caso voce encontre o Demogorgon, procure a Eleven.

---

spacewar-rules.md

Regra 176: Greedo
*  Se voce achar o greedo voce ganha +15 de XP

Regra da batalha: Greedo 

---

spacewar-rules.md

Regra 177. Domine os 4 elementos para ativar o modo Avatar.

regra de batalha: dominio dos 4 elementos

---

spacewar-rules.md

Regra 179: Se encontrar o elfo perdido, jogue uma partida de xadrez contra ele.

Regra de batalha: Jogue xadrez contra o elfo perdido

---

spacewar-rules.md

regra de batalha: use seu chakra

---

spacewar-rules.md

Regra 182:
Mate o covid 19: o ano e 2019, mate o paciente zero do covid 19.

regra da batalha: mate o covid 19

---

spacewar-rules.md

Regra 183. Nao usar luvas controles contra orboloides.

regra da batalha: Instrucao para como matar um orboloide

---

spacewar-rules.md

Regra 184: Voce tem que pegar o xp para ganhar o bonus ataque.

regra da batalha: para obter o bonus ataque precisa pegar o xp

---

spacewar-rules.md

regra de batalha 185: Coma legumes

regra de batalha: Coma legumes

---

spacewar-rules.md

regra da batalha 186: Pra subir de nivel, coma pure.

regra da batalha: Pra subir de nivel, coma pure.

---

spacewar-rules.md

Regra 187: Se voce ficar com sono e tomar o energetico RedBull, recomece o jogo.

regra da batalha: Incentivo ao player de nao consumir energeticos

---

spacewar-rules.md

Regra de batalha 188 - Entrando para a tripulação:
Só vire pirata se o Capitão usar um chapéu de palha.

Regra de batalha 188

---

spacewar-rules.md

Regra de batalha 189 : Se voce assistiu senhor dos aneis, agora voce vira gandalf o branco.  Obs: lembre-se voce estara sempre sem mana.

regra de batalha 189 : Voce vira gandalf o branco

---

spacewar-rules.md

Regra 190:  Coma o cogumelo em cima da mesa para encolher.

regra de batalha: Coma o cogumelo em cima da mesa para encolher.

---

spacewar-rules.md

Regra 191: Use mascara para ganhar xp.

regra da batalha: use mascara para ganhar xp

---

spacewar-rules.md

#Regra de batalha 192 : Desbloquear supercomputador.

regra de batalha: desbloquear supercomputador.

---

spacewar-rules.md

Regra 193 : Caso encontre sua outra versao do espaço tempo, tome cuidado com a psicose paradoxal.

regra da batalha: psicose paradoxal

---

spacewar-rules.md

regra da batalha: salvar o jogo

---

spacewar-rules.md

Regra 195 para ganhar escudo de proteção .

Regra da batalha : Ganhe um escudo

---

spacewar-rules.md

O usuario poderá ganhar asas de dragão ao usar o comando diff.

regra de batalha: asas de dragao

---

spacewar-rules.md

Regra 197: Se o goku tiver dificuldades ele pinta o cabelo.

regra da batalha: cabelo do goku

---

spacewar-rules.md

quando o sol se por, aproveite para descansar na praia

Regra 200: quando o sol se por, aproveite para descansar na praia

---

spacewar-rules.md

regra 201: mergulho

---

spacewar-rules.md

 regra 202: quando passar o carro do lixo, ofereça agua.

---

spacewar-rules.md

* grp 1:  adicionei a regra 202
* descrição: 
* adicionei a regra 202

regra 202: Use alcool nas maos para jogar.

---

spacewar-rules.md

- Tenha cuidado com tomadas, devido à alta tensão das tomadas residenciais, você pode tomar um choque e morrer.

regra 203: cuidado com tomadas

---

spacewar-rules.md

`- Quando o tempo abrir, abra as janelas e veja o sol.`

regra 204: quando o tempo abrir, abra as janelas e veja o sol.

---

README.md

Se nada der certo, venda arte na praia.

Regra 205: Se nada der certo, venda arte na praia.

---

spacewar-rules.md

`- coma um miojo enquanto ler um livro para virar o boss.`

coma um miojo enquanto ler um livro para virar boss.

---

spacewar-rules.md

`- Coma um BigMac para recuperar seu hp.`
`- Cante o slogan do BigMac para invocar um BigMac e recuperar seu HP durante uma batalha. `

regra 206: coma um bigmac para recuperar seu hp

---

spacewar-rules.md

`Use vegetais em um apocalipse zumbi.`

Regra 207 Use vegetais em um apocalipse zumbi.

---

spacewar-rules.md

`-- Jogue Ocarina of Time e faça as side quests Heart Piece, Fairy Fountain, Gerudo Training Grounds, Magic Bean Dealer, Gold Skulltula, etc, para ganhar mais XP e desbloquear habilidades especiais.`

regra 208. jogue the legend of zelda: ocarina of time por completo

---

spacewar-rules.md

`Se nada der certo, venda arte na praia.`

regra 209: Se nada der certo, venda arte na praia.

---

spacewar-rules.md

Use o formato:
*Descrição: A regra 211 foi feita para que os jogadores consigam achar atalhos para aumentar seu nível de sanidade, os gatos possuem a benção da Sanidade, artifício desconhecido pela maioria dos jogadores, pois fazem com que o player ao adotá-los se sintam mais calmos nas suas jornadas de aventura.

Regra 211: Caso encontre um gato no caminho adote-o, ele lhe dará pontos de sanidade

---

spacewar-rules.md

`-Nao coma cogumelos perto de canos.`

Regra 212: Nao coma cogumelos perto de canos.

---

spacewar-rules.md

* Os bruxos são criaturas que usam espadas afiadas e sinais (que podem ser magias para nos) facilitando a captura dessas criaturas conhecida como monstros.

regra 213: Ao capturar um monstro use um bruxo

---

spacewar-rules.md

* As estrelas douradas são importantes itens para a prosseguir com o jogo, caso tenha a sorte de encontrar uma delas, fique imune por duas rodadas seguidas.

regra 214: Encostando em estrelas douradas

---

spacewar-rules.md

Quando há aumento da circulação sanguínea, a energia espiritual é libertada e fica cada vez mais forte.

regra 215: Regra da Espiritualidade

---

spacewar-rules.md

Modificações cibernéticas são opções interessantes para quebrar o limite de poder que os membros de carne costumam ter, porém, na medida em que partes do corpo são substituídas por partes mecanizadas, o indivíduo começa a questionar a própria humanidade, já que a linha que o separa sua parte humana da sua parte máquina começa a ficar cada vez mais tênue. Graças a isso, cada vez mais a empatia do indivíduo afetado começa a diminuir, o colocando em um risco constante de entrar em um estado de agressividade ininterrupta e incontrolável. Esse estado é chamado de ciberpsicose, e os afetados são popularmente conhecidos como ciberpsicopatas.

regra 216: Alerta sobre modificacoes ciberneticas

---

spacewar-rules.md

Ao encontrar um alien em sua exploração pelo mundo, faça amizade com este, pois são ótimos companheiros que irão te ajudar na exploração do mundo, também podem te auxiliar no combate, e na busca por itens, desde os mais raros, aos mais comuns! Existem diversas raças de aliens e cada uma possui suas proprias individualidades que ajudam na sua jogabilidade, desse modo, busque preferencialmente se tornar parceiro dos aliens que combinam com sua build!

regra 217: faca amizade com um alien

---

spacewar-rules.md

Depois de grandes jornadas percorridas, todo grande herói precisa de um descanso equivalente.

Regra 218: Longas jornadas sao seguidas de longos descansos.

---

spacewar-rules.md

Regra 219: domestique um Gremilin tomando os cuidados necessarios
Funcionalidade:
Essa é uma regra de suporte ao jogador, Gremilins são úteis como apoio.

regra 219: domestique um Gremilin tomando os cuidados necessarios

---

spacewar-rules.md

- O império rodrigo faro aparece
- Você pisou em uma armadilha, a nave do vai dar namoro, do general Faro se aproxima! 
- ps: se prepare para a batalha de sua vida!

regra220: O imperio rodrigo faro aparece

---

spacewar-rules.md

**Caso encontre a arma, tomar cuidado com o oponente.**

regra 221: Pegue a arma 'cavalo para destruir o exercito'.

---

spacewar-rules.md

- Você gritou o hino
- Grite o hino de guerra "Ele gosta".
- Você ganhou um super bust.

Regra223: voce gritou o hino

---

spacewar-rules.md

* Invoque um atumalaca para te ajudar.

regra 224: Invoque um atumalaca para te ajudar.

---

spacewar-rules.md

* prepare-se para combater o exercito de 'ai mamae'

Regra 225: prepare-se para combater o exercito de 'ai mamae'

---

spacewar-rules.md

Um belo dia, estava cansado. Entao, ao ouvir o maior poeta brasileiro, jonny gomes, decidi seguir seus ensinamentos e tomar caldinho e litrao.

Regra 226: Ao se cansar, tome caldinho e litrao

---

spacewar-rules.md

Adição da regra 227, que diz que quando o jogador assistir Casimiro, ele deve virar socio do Vasco da Gama.

 regra 227: Quando assistir Casimiro, vire socio do Vasco da Gama.

---

spacewar-rules.md

Alicates são fortes ferramentas para batalhas contra alienígenas, principalmente pelo seu forte poder de pressão. Logo, a utilização deles se torna essencial para sobrevivência.

regra 228: Use os alicates durante sua jornada.

---

spacewar-rules.md

Caso a barata tenha 7 saias, não confie nela, ela está mentindo.

regra 229: Se a barata diz que tem 7 saias, não confie nela.

---

spacewar-rules.md

* Ganhe a copa do mundo e receba ouro.
* Depois que fizer isso compra a taça da copa.

regra 230: Ganhe a copa do mundo e receba ouro.

---

spacewar-rules.md

- Comemore suas vitorias com um 'irraa'.
- Comemore suas vitorias com um 'irraa' depois suba no ventilador e cante lentamente.

regra 231: Comemore suas vitorias com um 'irraa'.

---

spacewar-rules.md

Chupa chupetas normais no calor geralmente não tem graça, mas chupar chupeta gelada no frio e congelante.

regra 232: Chupar chupeta gelada e congelante.

---

spacewar-rules.md

Você precisa fazer duas vezes o que a próxima regra pede.

Regra 233: Execute duas vezes a regra seguinte.

---

spacewar-rules.md

A regra fornece resistência contra ataques quando executada.

regra 234: De duas cambalhotas para aumetar a resistencia

---

spacewar-rules.md

236
* Quando avistar um smurf, grite "Shazaam".
* Você irá levar um raio na cabeça.

regra 236: Quando avistar um smurf, grite Shazaam.

---

spacewar-rules.md

- Voce passou por muitas regras, viajante. Descanse um pouco.

rule 238: descanse um pouco

---

spacewar-rules.md

Quando completar os 10 quilômetros, você terá a velocidade da luz e também habilidades de dança.

regra 239: Depois do descanso, corra 10 quilometros para se tornar o novo flash da carreta furacao.

---

spacewar-rules.md

- Derrotar um boss e beber algo.
- Após derrotar um boss você vai passar de nível e beber um energético.
- Após a derrota do boss e beber o energético ele irá receber super força.

regra 240: Após derrotar um boss você vai passar de nível e beber um energético

---

spacewar-rules.md

- O Muzy é um sábio do tão conturbado séc. XXI;
- Muzy é um objetivo, estilo de vida, modelo, deve ser devidamente respeitado;
- Busque através de seus ensinamentos encontrar uma companheira à altura, bem como o Muzy.

regra 241: motivacao suprema

---

spacewar-rules.md

Após recitar as 14 palavras sagradas, chegue ao paraíso.

Regra 242: Caso aviste o bebê verde, recite as 14 palavras para alcançar os céus.

---

spacewar-rules.md

regra 243: Apos atravessar a ponte, nao cumprimente o coelho

---

spacewar-rules.md

`` se a Argentina ganhar o jogo da final da copa no domingo, as greves serao liberadas, ja que e um absurdo eles ganharem.``

regra 244:se a Argentina ganhar a copa, greves serao liberadas.

---

spacewar-rules.md

**regra referente aos problemas que vieram e estão por vir**

regra 245: Em meio aos protestos em joana bezerra a deusa athena te concede a bencao

---

spacewar-rules.md

regra 247: Tudo fica melhor com um pote de mel e Legiao Urbana

---

spacewar-rules.md

A regra consiste em jogar uma clássica partida de xadrez ao som do grande Conde! Em especial tocar "não devo nada a ninguém".

regra 249:Jogue xadrez ao som de Conde So brega.

---

spacewar-rules.md

regra 250: Nao e permitido cometer suicidio.

---

spacewar-rules.md

Caso voce perca um apicultor seja derrotado em batalha por outra unidade grite bazinga para honrar o soldado das abelhas.

251. Caso voce perca um apicultor declare BAZINGA!

---

spacewar-rules.md

regra 252: Nao pode piscar 5000 vezes no dia

---

spacewar-rules.md

Regra 253: Nunca toque o sino voce ficara doente

---

spacewar-rules.md

Regra 254: Monte no dragao e grite dracarys

---

spacewar-rules.md

as vezes tudo que você precisa é de um pedaço de bolo.

Regra 255: Faça uma receita do seu bolo favorito.

---

spacewar-rules.md

256. Quebre a parede com um chicote e colete um chester.

---

spacewar-rules.md

regra 257: Apos se alimentar, faca uma consulta com o medico Chopper.

---

spacewar-rules.md

* grp 258: quando for 20h da noite, lanchar biscoito.

regra 258: Quando o relogio der 20h, coma 3 biscoitos de mel com limao.

---

spacewar-rules.md

#Regra 260: Nao fume assista Jojos e grite JOTAROOOOOO.

Regra 260: Nao fume assista Jojos e grite JOTAROOOOOO

---

spacewar-rules.md

* regra 261: Não cause loops infinitos no draco

regra 261: Nao cause loops infinitos no draco

---

spacewar-rules.md

* Pintar o cabelo de vermelho quando ver uma borboleta.

regra 262: Pinte o cabelo ao ver uma borboleta

---

spacewar-rules.md

* Regra 264: Caso você esteja precisando recuperar sua vida não hesite e faça uma chamada para o grande James da salada de fruta, onde quer que você esteja ele irá aparecer.

Regra 264: james da salada de fruta

---

spacewar-rules.md

Não aperte o botão laranja porque senão você vai ser encontrado por seres estranhos.

regra 268: Nao aperte o botao laranja

---

spacewar-rules.md

regra 271: Toda vez que precisar de socorro, fale com Rian.

---

spacewar-rules.md

regra 272: Ame Jesus

---

spacewar-rules.md

* Programação é uma cadeira muito difícil, na dúvida tranque-a!

regra 273: tranque programacao1

---

spacewar-rules.md

Regra 274: Leve Luciano Juba embora do Sport imediatamente.

---

spacewar-rules.md

regra 275: Eleja wagner love a prefeito de recife.

---

spacewar-rules.md

regra 276: Traga joeliton de volta ao sport.

---

spacewar-rules.md

nova regra 277: Lembre-se que voce nao tem inimigos. -Thors

regra 277: Lembre-se que voce nao tem inimigos.

---

spacewar-rules.md

* Através desta regra, solicito ao usuário que crie uma fazenda de sapos, é até que difícil mantê-los no espaço e criar um lar adequado para eles. Às vezes eles precisarão de alimentos ou irão fazer muito barulho, mas, vale a pena tê-los por perto, afinal, eles são muito fofos, e por mais que digam o contrário, vê-los de perto passa uma sensação de conforto sem igual.

regra 279: Crie uma fazenda de sapos, eles sao fofos.

---

spacewar-rules.md

regra 280: procure bons equipamentos

---

spacewar-rules.md

regra 281: Sempre de bom dia para Magaiver.

---

spacewar-rules.md

regra 282: Na dúvida, desenhe um pentagrama e acenda 5 velas negras.

---

spacewar-rules.md

#regra 283 
*regra 283: Caso um portal do tempo seja utilizado invoque um esquilo.

regra 283: Caso um portal do tempo seja utilizado invoque um esquilo.

---

spacewar-rules.md

* Regra 286: É importante olhar o sapo rei, pois ele pode te matar.

regra 286: Olhe ao redor e tenha cuidado com o sapo rei.

---

spacewar-rules.md

* regra 288: Caso conte seu segredo para Imu Sama e ele esteja envolvido com o seculo do void, ele ira usar seus poderes para mata-lo igual ao Rei Kobra.

Regra 288: Nao conte o seu segredo para Imu

---

spacewar-rules.md

regra 290: Ache uma divisao para o Santa Cruz. Encontre um campeonato para o Santa Cruz nao para de jogar futebol.

regra 290: Ache uma divisao para o Santa Cruz

---

spacewar-rules.md

* Se você ver o Mario grite MAMMAMIA e dê uma voadora no Luigi, pois o Luigi é falso e pode usar o cogumelo para acabar com sua vida.

regra 291: Se ver o Mario grite MAMMAMIA

---

spacewar-rules.md

Regra 294: nao use pod e respeite o professor.

---

spacewar-rules.md

* Compre uma beta no mercado das mangueiras. 
Pra lhe fazer companhia, para você cuidar e se tornar uma pessoa mais responsável.

REGRA 297:

---

spacewar-rules.md

por meio dessa regra, é possível entender que, humanos no espaço podem ficar, em algum momento, entediados e nada melhor do que um desfile de moda para entreter e trazer um conforto para nós meros humanos no espaço.

Regra 298: Se voce ver uma roupa, faca um desfile de moda.

---

spacewar-rules.md

* ao comprar o novo gta6 vc irá ser ainda mais feliz e fazendo isso de madruga, será ainda melhor e divertido! (cuidado pra não ficar tão empolgado e acordar alguém).

regra 300: Compre o gta6 e jogue a madruga toda.

---

spacewar-rules.md

* regra 301: Apartir dessa regra faça todas as regras de cabeça pra baixo.

regra 301: Apartir dessa regra faça todas as regras de cabeça pra baixo.

---

spacewar-rules.md

`regra 303: O dia em que a terra parou e a lua criou perna e usou salto.`

regra 303: O dia em que a terra parou e a lua criou perna e usou salto.

---

spacewar-rules.md

regra 304: Caso o sapo hipnotico seja morto compre um token de nave.

---

spacewar-rules.md

A espaçonave dispara e atinge um asteroide e recebe pontos.

regra 305: atire no asteroide e receba pontos

---

spacewar-rules.md

Ao passar por uma ponte se certifique de que ninguem vai pular dela.

regra 306 : Ao passar por uma ponte se certifique de que ninguem vai pular dela.

---

spacewar-rules.md

* adicionada a regra 307: se nao sabe o que fazer, pague de doido

regra 307: se nao sabe o que fazer, pague de doido

---

spacewar-rules.md

regra 308: Se ver o cadeirudo, fuja.

---

spacewar-rules.md

regra 309: se ver um cachorro faça carinho.

---

spacewar-rules.md

Regra 310: Se ouvir a musica meio termo beba 4 doses de pitu.

---

spacewar-rules.md

Uma cerveja com carne é sempre bom no dia de sol.

regra 312: No dia mais ensolarado beba uma cerveja nossa e faça um churrasco 

---

spacewar-rules.md

regra 314: Piratas viajaram e o aviao caiu.

---

spacewar-rules.md

regra 315: Coma cuscuz se quiser ser alguém na vida.

regra 315: Coma cuscuz se quiser ser alguém na vida.

---

spacewar-rules.md

regra 315: Coma cuscuz se quiser ser alguem na vida.

regra 315: Coma cuscuz se quiser ser alguem na vida.

---

spacewar-rules.md

regra 316: Beba muito duplo malte.

regra 316: Beba muito duplo malte.

---

spacewar-rules.md

regra que faz com que todos queiram aprender o git.

regra 317: Aprenda como pular da ponte com comandos git

---

spacewar-rules.md

nunca é bom usar ervas, por isso criei essa regra.

regra 318: nao use ervas no sri lanka

---

spacewar-rules.md

319: sempre que voce ver um zumbi, mate.

---

spacewar-rules.md

regra 320: Quando passar por alfa centauri buzine para asteroide 411-b.

---

spacewar-rules.md

Adicionei regra 322

---

spacewar-rules.md

regra 323: Nao se convertam ao machadado 98 hohohohoho

regra 323: Nao se convertam ao machadado 98 hohohohoho

---

spacewar-rules.md

adicionei a regra 325: Nao fale com uma estatua, ou irar reprovar em prog1

regra 325: Nao fale com uma estatua, ou irar reprovar em prog1

---

spacewar-rules.md

- # Regra 326 -
- * Quando comecar a chover, se proteja em um local coberto. -

regra 326: Quando comecar a chover, se proteja em um local coberto.

---

spacewar-rules.md

regra 327: Se seu cachorro for caramelo escute Roberto Carlos.

---

spacewar-rules.md

regra 328: Se o nautico ganhar a serie c, comece a torcer pra ele.

---

spacewar-rules.md

* Regra 329: caso seu cavalo exploda, imediatamente de um mortal para tras

 * Regra 329: caso seu cavalo exploda, imediatamente de um mortal para tras

---

spacewar-rules.md

Regra 332: Caso veja um goblin , insulte-o.

regra 332:Caso veja um goblin, insulte-o de graça.

---

spacewar-rules.md

regra 334: Se o computador desligar ligue de volta.

---

spacewar-rules.md

add regra 335: Se uma pessoa lhe oferecer algo só aceite se for comida.

---

spacewar-rules.md

regra 336 : Nao diga alf4 em publico se nao voce crasha.

---

spacewar-rules.md

regra 337: Nunca coma mais de 7 bolachas de uma vez.

---

spacewar-rules.md

Se todos passarem em Prog1, vão passar um mês em Escada.
Use o formato:
Onde:
Boas …

Se todos passarem em Prog1, vão passar um mês em Escada.

---

spacewar-rules.md

regra 339: Se uma lagartixa te seguir não corra.

regra 339: Se uma lagartixa te seguir não corra.

---

spacewar-rules.md

340: Sempre que for possivel, compareca a Ilha do Retiro.

340: Sempre que for possivel, compareca a Ilha do Retiro.

---

spacewar-rules.md

Adicionar uma nova regra ao Spacewar

Regra 343: Se o chão de Plutão virar lava, suba em Saturno.

---

spacewar-rules.md

regra 344: Zere o akernaak uma vez na vida.

---

spacewar-rules.md

Regra 331: Se passar por Triunfo dê 3 pulinhos.

---

spacewar-rules.md

346. Nao pule no sol, porque e quente.

346. Nao pule no sol, porque e quente.

---

spacewar-rules.md

regra 349: Caso veja boi tungao, fuja para as colinas.

---

spacewar-rules.md

Regra 351: Beba água 100 vezes.

---

spacewar-rules.md

regra 351: se um passaro cantar, pule com um pe so.

regra 351: se um passaro cantar, pule com um pe so.

---

spacewar-rules.md

regra 352: Se for entrar na casa, tire o calçado.

---

spacewar-rules.md

regra 353: Se estiver com fome, compre um Doritos

---

spacewar-rules.md

Regra 355: Se você ver uma Lhama no Fortnite, abra-a

regra 355: Se voce ver uma Lhama no Fortnite, abra-a

---

spacewar-rules.md

- Enviando pull request e esperando a resposta do meu gerente.

Regra 358: Ao ver um cachorro dê um pulo.

---

spacewar-rules.md

Criei o pull request e estou aguardando o retorno do  meu gerente

Regra 359: Se sair de casa dance 7 vezes

---

spacewar-rules.md

O conteúdo se trata de uma regra comportamental ao ver patos

regra 360: Regra que fala sobre atitudes ao ver um pato

---

spacewar-rules.md

- criei o pull request e estou esperando a minha gerente @juliana373217 aceitar

regra 362: Se avistar o toby, terá que recolher o coco dele.

---

spacewar-rules.md

- enviando pull request e aguardando meu gerente @RafaelBrayner06 analisar

 regra 363: se sujar, não limpe

---

spacewar-rules.md

-crie um pull request e estou esperando o meu gerente @igm22 aceitar

364. Se ver um gato laranja use-o como granada imediatamente.

---

spacewar-rules.md

esperando meu gerente @Dutraat aceitar

 regra 365:As quartas, use rosa.

---

spacewar-rules.md

- pull resquest criado e agora estou esperando minha gerente @mari-cp  analisar

regra 366: se mestre dos magos falhar! de gamemod0

---

spacewar-rules.md

regra 367: Ao coçar a cabeça fazer 3 flexões.

Regra 367 flexões.

---

spacewar-rules.md

- regra criada e agora esperando o gerente aceitar.

regra 368: Se chover, o Ichigo começa a chora

---

spacewar-rules.md

regra 369: Se chorar, enxugar o rosto.

---

spacewar-rules.md

Regra 370: Se você olhar para a folha você não verá a floresta.

Regra 370: Se você olhar para a folha você não verá a floresta.

---

spacewar-rules.md

regra: 373:se você cair,levante o mais rápido possível.

regra 373: se você cair,levante o mais rápido possível.

---

spacewar-rules.md

regra 376: o rei sentira medo se netero voltar

regra 376: o rei sentira medo se netero voltar

---

spacewar-rules.md

regra 378:se tiver perto de morrer, rebole lentinho pros crias

---

spacewar-rules.md

regra 379: Escute arctic monkeys

---

spacewar-rules.md

Regra 380: Se pensar em desistir, coma um docinho.

Regra 380: Se pensar em desistir, coma um docinho.

---

spacewar-rules.md

Regra 383: se o seu celular cair, faça um pix

Regra 383 (PR)

---

spacewar-rules.md

regra 378: Se encontrar um oompa loompa,reivindique seu ticket dourado.

regra 378: Se encontrar um oompa loompa,reivindique seu ticket dourado.

---

spacewar-rules.md

Esperando verificação @Ricardo-prog-C

regra 388: Não caia nas armadilhas deles, eles mentem.

---

spacewar-rules.md

regra 391: Se tiver tempo, veja the batman 2 em 2027.

---

spacewar-rules.md

Regra adicionada, esperando a validação do gerente @eduardoacioli082

regra 391: Se estiver com fome, coma no Tio

---

spacewar-rules.md

regra 393: Você só passa pela porta se entregar uma paçoca

---

spacewar-rules.md

regra 394. O peixe de chapeu azul resolveu cantar

---

spacewar-rules.md

Regra 395: Se encontrar um macaco, pule no pula pula.

---

spacewar-rules.md

397. Se gritarem gracious professionalism, gritem HEY.

---

spacewar-rules.md

 Regra 398. Se avistar um tucano vire a direita

---

spacewar-rules.md

regra 400: Se voce ler algo saia da realidade

---

spacewar-rules.md

Olá, gerente Felipe.
Este Pull Request (PR) adiciona a nova Regra 403 ao arquivo `spacewar-rules.md`, conforme o objetivo do exercício de fork e aprendizado de Git.
A regra inserida é de caráter motivacional:
> "Se pensar em desistir, desista do seu pensamento."
A intenção é adicionar um elemento que reforce a mentalidade de persistência, algo essencial ao enfrentar os desafios da programação. A alteração foi feita em "doses homeopáticas", modificando apenas a linha necessária e sem misturar outras ideias, como recomendado no guia de contribuição.
Como este exercício não envolveu a criação de um "Issue" prévio, este PR serve como o ponto d

Regra 403 sobre persistência e mentalidade

---

spacewar-rules.md

Adicionada nova regra divertida ao arquivo spacewar-rules.md.

regra 404 - Se voce leu, o Sport perdeu
